### ISSUE TITLE
Loop through array of elements and their promises

### ISSUE THREAD

**Issue by isvaljek** [thisconnect/nodegit-kit#16]
How can I handle an array of commits that each have their own .then() handler, and possibly loop each of the child elements with again their own then() handlers?
I tried with recursive functions but my problem is multiple nested loops like displaying all commits in a repo then all the diffs in each commit.

**Comment by isvaljek** [comment]
Can you tell me at least which library (if any) are you using for promises?

**Comment by thisconnect** [comment]
Hi

> How can I handle an array of commits that each have their own .then() handler, and possibly loop each of the child elements with again their own then() handlers?

I believe you are looking for Promise.all 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

> Can you tell me at least which library (if any) are you using for promises?

NodeGit-Kit is using Node.js (v8) native Promises, that means it will only work with newer versions of Node.js

This should give you all commits, diffing to the last commit.

```javascript
git.open(dir)
.then(repo => {
  return git.log(repo)
  .then(history => history.map(log => {
    return log.commit;
  }))
  .then(commits => {
    console.log(commits) // all commit id's
    const lastCommit = commits[commits.length - 1]
    return Promise.all(commits.map(commit => {
      return git.diff(repo, commit, lastCommit)
    }))
  })
  .then(diffs => {
    console.log(diffs) // all diffs
  })
})

```

**Comment by thisconnect** [comment]
of corse if you use an older version of Node.js you could add a promise polyfill.

**Comment by isvaljek** [comment]
Thank you for this example, it seems that node has moved on since our last encounter :)
Are these 'repo =>' and 'history =>' constructs something like lambdas in C#?
The other problem is that for this repo (slick.js) and this example I get:
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory.
The last problem is connected to this error, because I would need to drill down at least one loop deeper and get all the files in the diff, I guess that's not going to help in the memory department, 
Can you give more insight into solving these kind of problems when working with large repos which must be drilled several levels deep? I would need file contents connected with their parent commit sha-s.

**Comment by thisconnect** [comment]
=> are es6 arrow functions

What are you trying to achieve. Can you post some code that I can reproduce your error?

**Comment by thisconnect** [comment]
You might run into problems if you have 500000000 commits. You might need to only do a few at the time.

**Comment by isvaljek** [comment]
I'm trying to download files from each commit in the repo into the folders named with the short sha of the commit.
The error I get is from this example you gave me. The test repo is this https://github.com/kenwheeler/slick
`var repo_dir = './repos/test1';
var commit_dir = './commits/test1';

var git = require('nodegit-kit');
var mkdirp = require('mkdirp');

git.open(repo_dir)
.then(repo => {
  return git.log(repo)
  .then(history => history.map(log => {
    return log.commit;
  }))
  .then(commits => {
    console.log(commits) // all commit id's
    const lastCommit = commits[commits.length - 1]
    return Promise.all(commits.map(commit => {
      return git.diff(repo, commit, lastCommit)
    }))
  })
  .then(diffs => {
    console.log(diffs) // all diffs
  })
})`

**Comment by thisconnect** [comment]
I am not familiar with the CALL_AND_RETRY_LAST JavaScript heap out of memory. but guess that it has to do that you want all 791 at once. I assume it doesnt happen with git.log but with a proomise of 791 commits.  you should probably chunk them into smaller parts and mabe only ask for 20 or 40 diffs at the time.

**Comment by thisconnect** [comment]
i do not believe this is a bug with https://github.com/nodegit/nodegit but they could tell you more about this error. I close this issue ok?

**Comment by thisconnect** [comment]
fyi i am able to read and diff 154 commits at the time without any error.

**Comment by isvaljek** [comment]
ok will try to create global var commits, and then chunk the promises, thank you.

**Comment by thisconnect** [comment]
last but not least. I tried with slick and got no error. osx and latest node.js

**Comment by isvaljek** [comment]
probably more ram in your machine, I'm running in a VM with 2GB

**Comment by isvaljek** [comment]
sorry to be pita but can you please tell me why does git.dff of first two commits here return empty diffs array? https://github.com/kenwheeler/slick/commits/master
commits: f6db519a and a0212e8 have empty diffs
but b6569fd has one diff
?

**Comment by thisconnect** [comment]
Closing as it s no nodegit-kit bug

**Comment by thisconnect** [comment]
Oh didnt see your message. I keep it ipen until i get a chance to look at it

**Comment by thisconnect** [comment]
> why does git.dff of first two commits here return empty diffs array? https://github.com/kenwheeler/slick/commits/master
commits: f6db519a and a0212e8 have empty diffs
but b6569fd has one diff

Not sure and i couldn't find the commits you mentioned on github. So I have no idea what the correct result should be. BTW: The code I pasted  is not what you want. My example diffed all commits against lastCommit (which actually is the first commit ever made).

If I understand you correctly you want `git log -p` (added new issue #17)
Also there is a bug with git.diff <from> <to> is currently switched. (#18) 
I close this

**Comment by thisconnect** [comment]
btw tested with this code

```javascript
var git = require('nodegit-kit');
var resolve = require('path').resolve;

git.open(resolve(__dirname, './test'))
.then(repo => {
  return git.log(repo)
  .then(history => history.reverse())
  .then(history => history.map((log, i) => {
    const next = history[i + 1]
    console.log(log.commit, next ? next.commit : null)
    return git.diff(repo, log.commit, next ? next.commit : null)
    .then(diff => {
      return { log, diff }
    })
  }))
  .then(items => Promise.all(items))
  .then(data => data.forEach(item => console.log(`
    ${item.log.commit.slice(0, 8)} ${item.log.message}
    ${item.diff.map(d => {
      return `
        ${d.status} ${d.path}
        index ${d.sha1.slice(0, 6)}..${d.sha.slice(0, 6)}
        ${d.hunks}
      `
    }).join('\n')}
  `)))
})
.catch(err => console.log(err))

```
