### ISSUE TITLE
merge question.

### ISSUE THREAD

**Issue by zhaopengme** [thisconnect/nodegit-kit#38]
I have a merge question.
e.g.

remote/master   modify A.txt  
master   modify A.txt

merge.merge('master','remote/master')   

A.txt is a conflict file.

I want to auto merge,and use the lastest file.

so  how to do ?

thanks!

**Comment by thisconnect** [comment]
nodegit-kit does not provide any merge methods. Please open an issue at https://github.com/nodegit/nodegit

**Comment by zhaopengme** [comment]
ok.thanks!
